
# Basic
name:               "Franklin Antony's Blog"
description:        "the writings of a developer."

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//franklinantony.me/blog"
author:             "beingfranklin"
twitter:
  username:         "beingfranklin"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            "/blog"
#baseurl:            "" #For Root Domain
permalink:          /:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Home Page"
    href:           "//franklinantony.me/" 
                   
  - name:           "Coming Soon"
    href:           ""

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
- jekyll-seo-tag



